name: CIxTools_auto
channels:
    - defaults
    - intel
    - conda-forge
    - bioconda
    - bokeh
    - rdkit
prefix: /Users/eric/opt/anaconda3/envs/SignelIX_CIx/envs/SignelIx_CIx

dependencies:
    - pip
    - pip:
      - -r file:requirements.txt
#conda env remove -n CIxTools_auto